[package]
name = "mini-aurora-wal"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-aurora-common = { path = "../common" }
crc32fast = "1"
tracing = "0.1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
