[package]
name = "mini-aurora-compute"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-aurora-common = { path = "../common" }
tokio = { version = "1", features = ["sync"] }
async-trait = "0.1"
tracing = "0.1"
thiserror = "2"
anyhow = "1"
