[package]
name = "mini-aurora-pagestore"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-aurora-common = { path = "../common" }
mini-aurora-wal = { path = "../wal" }
moka = { version = "0.12", features = ["sync"] }
tracing = "0.1"
thiserror = "2"
